DB_USER = "test_user"
DB_USER_PASSWORD = "test_pass"
DB_IP_ADDRESS = "localhost"
DB_TABLENAME = "asm4deaf"

SESSION_ENCRYPTION_SECRET_KEY = "wuMn!4xc#sEUhG4@Y@&pdi&^"
USER_SESSION_LIFETIME_IN_DAYS = 1

GIF_FILEPATH_ROOT = ".\GIFs\\"